import Products from '@/components/Home/Products';
import React from 'react';

export const metadata = {
    title: "All Product",
    description: "Generated by create next app",
  };
  

const ProductPage = () => {
    return (
        <div>
            <Products></Products>
        </div>
    );
};

export default ProductPage